# Generated by Django 4.2.4 on 2023-09-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Customer Name', max_length=64)),
                ('birthdate', models.DateField(help_text='Customer Birthdate', verbose_name='Birthday')),
                ('email', models.EmailField(help_text='email address of the customer', max_length=254)),
            ],
        ),
    ]
